
@baseUrl = http://localhost:7071
@contentType = application/json
@documentName = document-translation-sample.docx
@userId = 00648f52-2627-48d6-a29e-f9d499b58057
@language = fr
@translationId = b3a2284b-ea5a-46f9-8805-048a163812ab

GET {{baseUrl}}/api/health
Content-Type: {{contentType}}


GET {{baseUrl}}/api/formats
Content-Type: {{contentType}}

GET {{baseUrl}}/api/languages
Content-Type: {{contentType}}

POST http://localhost:7071/api/start_translation
Content-Type: application/json

{
  "blob_name": "document-translation-sample.docx",
  "user_id": "00648f52-2627-48d6-a29e-f9d499b58057",
  "target_language": "fr"
}


GET http://localhost:7071/api/check_status/d480fe2f-dc07-4236-b6fc-4a5f8eb371bb



POST {{baseUrl}}/api/get_result
Content-Type: application/json

{
  "blob_name": "document-translation-sample.docx",
  "user_id": "00648f52-2627-48d6-a29e-f9d499b58057",
  "target_language": "fr"
}



GET {{baseUrl}}/api/get_result?blob_name=document-translation-sample.docx&target_language=fr&user_id=00648f52-2627-48d6-a29e-f9d499b58057


